# Generated by Django 4.2.8 on 2023-12-24 14:50

import bankapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnal',
            name='materials_provide',
            field=models.CharField(max_length=100, verbose_name=bankapp.models.Material),
        ),
    ]
