# Generated by Django 4.2.8 on 2023-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_personnal_materials_provide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='wikipedia_link',
        ),
        migrations.AddField(
            model_name='district',
            name='wikipedia_link',
            field=models.URLField(default=2333),
            preserve_default=False,
        ),
    ]
