# Generated by Django 4.2.8 on 2023-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_remove_branch_wikipedia_link_district_wikipedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='wikipedia_link',
        ),
        migrations.AddField(
            model_name='branch',
            name='wikipedia_link',
            field=models.URLField(default=4444),
            preserve_default=False,
        ),
    ]
