# Generated by Django 4.2.8 on 2023-12-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_remove_district_wikipedia_link_branch_wikipedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnal',
            name='materials_provide',
        ),
        migrations.AddField(
            model_name='personnal',
            name='materials_provide',
            field=models.ManyToManyField(to='bankapp.material'),
        ),
    ]
