# Generated by Django 4.2.8 on 2023-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_remove_personnal_materials_provide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnal',
            name='materials_provide',
        ),
        migrations.AddField(
            model_name='personnal',
            name='materials_provide1',
            field=models.CharField(default=2222, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnal',
            name='materials_provide2',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnal',
            name='materials_provide3',
            field=models.CharField(default=222, max_length=100),
            preserve_default=False,
        ),
    ]
