# Generated by Django 4.2.8 on 2023-12-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_remove_personnal_materials_provide_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnal',
            old_name='account_type',
            new_name='AccountType',
        ),
    ]
